Document: osrm-backend
Title: Debian osrm-backend Manual
Author: <insert document author here>
Abstract: This manual describes what osrm-backend is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/osrm-backend/osrm-backend.sgml.gz

Format: postscript
Files: /usr/share/doc/osrm-backend/osrm-backend.ps.gz

Format: text
Files: /usr/share/doc/osrm-backend/osrm-backend.text.gz

Format: HTML
Index: /usr/share/doc/osrm-backend/html/index.html
Files: /usr/share/doc/osrm-backend/html/*.html
